'use client';

import React, { createContext, useContext, useState } from 'react';

type Language = 'EN' | 'IT' | 'PL' | 'ZH' | 'DE' | 'FR' | 'RU' | 'ES';

const translations: Record<Language, Record<string, string>> = {
  EN: {
    headerBranding: 'Well Done! We\'re Champion Region!!',
    headerSubtitle: 'Now let\'s try to recover from the mistakes made before it\'s too late',
    spiritualPowerTitle: 'Spiritual Power Management',
    spiritualPowerDesc: 'Learn how to manage your kingdom\'s spiritual power during events',
    guardWeapons: 'Guard Weapons',
    curiosities: 'Curiosities',
    coatsOfArms: 'Coats of Arms',
    newBadge: 'New',
    eventsTitle: 'What To Do During Events',
    eventsDesc: 'Equipment management strategies for keeping spiritual power low',
    guardWeaponsStrategy: 'Guard Weapons Strategy',
    guardWeaponsContent: 'Keep spiritual power low during events by:',
    equipStrategically: 'Equipping Guard Weapons strategically',
    manageTroops: 'Managing troop formations (Distanza, Cavalleria, Fanteria)',
    exceptionLeaders: 'Exception for leaders Cristian and Rasse',
    curiositiesManagement: 'Curiosities Management',
    optimizeCollection: 'Optimize your collection:',
    collectCombine: 'Collect and combine Curiosities',
    trackPowerChanges: 'Track spiritual power changes',
    planLoadouts: 'Plan event-specific loadouts',
    coaNew: 'Coats of Arms (New)',
    newestFeature: 'The newest feature for spiritual power control:',
    applyCoa: 'Apply Coats of Arms for bonus effects',
    calculateImpact: 'Calculate combined spiritual power impact',
    maximizePerformance: 'Maximize event performance',
    copyright: 'Guns of Glory',
  },
  IT: {
    headerBranding: 'Ben Fatto! Siamo in regione campioni!!',
    headerSubtitle: 'Ora proviamo a recuperare agli errori commessi prima che sia troppo tardi',
    spiritualPowerTitle: 'Gestione del Potere Spirituale',
    spiritualPowerDesc: 'Impara come gestire il potere spirituale del tuo regno durante gli eventi',
    guardWeapons: 'Armi della Guardia',
    curiosities: 'Curiosità',
    coatsOfArms: 'Stemmi',
    newBadge: 'Novità',
    eventsTitle: 'Come Fare Durante gli Eventi',
    eventsDesc: 'Strategie di gestione degli equipaggiamenti per mantenere basso il potere spirituale',
    guardWeaponsStrategy: 'Strategia Armi della Guardia',
    guardWeaponsContent: 'Mantieni il potere spirituale basso durante gli eventi:',
    equipStrategically: 'Equipaggiando Armi della Guardia strategicamente',
    manageTroops: 'Gestendo le formazioni di truppe (Distanza, Cavalleria, Fanteria)',
    exceptionLeaders: 'Eccezione per i leader Cristian e Rasse',
    curiositiesManagement: 'Gestione delle Curiosità',
    optimizeCollection: 'Ottimizza la tua collezione:',
    collectCombine: 'Raccogli e combina Curiosità',
    trackPowerChanges: 'Traccia i cambiamenti del potere spirituale',
    planLoadouts: 'Pianifica equipaggiamenti specifici per gli eventi',
    coaNew: 'Stemmi (Novità)',
    newestFeature: 'La nuova funzione per il controllo del potere spirituale:',
    applyCoa: 'Applica Stemmi per effetti bonus',
    calculateImpact: 'Calcola l\'impatto del potere spirituale combinato',
    maximizePerformance: 'Massimizza le prestazioni dell\'evento',
    copyright: 'Guns of Glory',
  },
  PL: {
    headerBranding: 'Świetnie! Jesteśmy Regionem Mistrzów!!',
    headerSubtitle: 'Teraz spróbujmy naprawić błędy popełnione zanim będzie za późno',
    spiritualPowerTitle: 'Zarządzanie Mocą Duchową',
    spiritualPowerDesc: 'Dowiedz się, jak zarządzać mocą duchową swojego królestwa podczas wydarzeń',
    guardWeapons: 'Broń Gwardii',
    curiosities: 'Osobliwości',
    coatsOfArms: 'Herbarze',
    newBadge: 'Nowe',
    eventsTitle: 'Co Robić Podczas Wydarzeń',
    eventsDesc: 'Strategie zarządzania uzbrojeniem aby utrzymać niską moc duchową',
    guardWeaponsStrategy: 'Strategia Broni Gwardii',
    guardWeaponsContent: 'Utrzymuj niską moc duchową podczas wydarzeń:',
    equipStrategically: 'Wyposażając Broń Gwardii strategicznie',
    manageTroops: 'Zarządzając formacjami wojsk (Distanza, Cavalleria, Fanteria)',
    exceptionLeaders: 'Wyjątek dla liderów Cristian i Rasse',
    curiositiesManagement: 'Zarządzanie Osobliwościami',
    optimizeCollection: 'Zoptymalizuj swoją kolekcję:',
    collectCombine: 'Zbieraj i łącz Osobliwości',
    trackPowerChanges: 'Śledź zmiany mocy duchowej',
    planLoadouts: 'Planuj obciążenia specyficzne dla ereigneń',
    coaNew: 'Herbarze (Nowe)',
    newestFeature: 'Najnowsza funkcja do kontroli mocy duchowej:',
    applyCoa: 'Stosuj Herbarze dla efektów bonusowych',
    calculateImpact: 'Oblicz połączony wpływ mocy duchowej',
    maximizePerformance: 'Zmaksymalizuj wydajność wydarzenia',
    copyright: 'Guns of Glory',
  },
  ZH: {
    headerBranding: '做得好！我们是冠军地区！！',
    headerSubtitle: '现在让我们尝试纠正之前犯下的错误，趁还不晚',
    spiritualPowerTitle: '精神力管理',
    spiritualPowerDesc: '学习如何在事件期间管理您的王国精神力',
    guardWeapons: '护卫武器',
    curiosities: '奇特物品',
    coatsOfArms: '纹章',
    newBadge: '新',
    eventsTitle: '事件期间的操作方法',
    eventsDesc: '装备管理策略以保持精神力低',
    guardWeaponsStrategy: '护卫武器策略',
    guardWeaponsContent: '在事件期间保持精神力低:',
    equipStrategically: '战略性地配备护卫武器',
    manageTroops: '管理部队编队 (远程、骑兵、步兵)',
    exceptionLeaders: '领袖 Cristian 和 Rasse 的例外',
    curiositiesManagement: '奇特物品管理',
    optimizeCollection: '优化您的收藏:',
    collectCombine: '收集并组合奇特物品',
    trackPowerChanges: '追踪精神力变化',
    planLoadouts: '规划特定事件的配置',
    coaNew: '纹章 (新)',
    newestFeature: '精神力控制的最新功能:',
    applyCoa: '应用纹章获得加成效果',
    calculateImpact: '计算综合精神力影响',
    maximizePerformance: '最大化事件性能',
    copyright: 'Guns of Glory',
  },
  DE: {
    headerBranding: 'Gut Gemacht! Wir Sind Championregion!!',
    headerSubtitle: 'Jetzt versuchen wir, die Fehler zu beheben, bevor es zu spät ist',
    spiritualPowerTitle: 'Verwaltung der Spirituellen Kraft',
    spiritualPowerDesc: 'Lerne, wie du die spirituelle Kraft deines Königreichs während Events verwaltest',
    guardWeapons: 'Wachausrüstung',
    curiosities: 'Kuriositäten',
    coatsOfArms: 'Wappen',
    newBadge: 'Neu',
    eventsTitle: 'Was Man Während Events Tun Sollte',
    eventsDesc: 'Ausrüstungsverwaltungsstrategien um die spirituelle Kraft niedrig zu halten',
    guardWeaponsStrategy: 'Wachausrüstungsstrategie',
    guardWeaponsContent: 'Halte die spirituelle Kraft während Events niedrig:',
    equipStrategically: 'Wachausrüstung strategisch ausrüsten',
    manageTroops: 'Truppformationen verwalten (Distanza, Cavalleria, Fanteria)',
    exceptionLeaders: 'Ausnahme für Anführer Cristian und Rasse',
    curiositiesManagement: 'Kuriositätenverwaltung',
    optimizeCollection: 'Optimiere deine Sammlung:',
    collectCombine: 'Sammle und kombiniere Kuriositäten',
    trackPowerChanges: 'Verfolge Veränderungen der spirituellen Kraft',
    planLoadouts: 'Plane ereignisspezifische Ausrüstungen',
    coaNew: 'Wappen (Neu)',
    newestFeature: 'Das neueste Feature zur Kontrolle der spirituellen Kraft:',
    applyCoa: 'Wende Wappen für Bonuseffekte an',
    calculateImpact: 'Berechne die kombinierte Auswirkung der spirituellen Kraft',
    maximizePerformance: 'Maximiere die Event-Leistung',
    copyright: 'Guns of Glory',
  },
  FR: {
    headerBranding: 'Bien Fait! Nous Sommes Région Championne!!',
    headerSubtitle: 'Maintenant, essayons de corriger les erreurs commises avant qu\'il ne soit trop tard',
    spiritualPowerTitle: 'Gestion du Pouvoir Spirituel',
    spiritualPowerDesc: 'Apprenez à gérer le pouvoir spirituel de votre royaume pendant les événements',
    guardWeapons: 'Armes de la Garde',
    curiosities: 'Curiosités',
    coatsOfArms: 'Blasons',
    newBadge: 'Nouveau',
    eventsTitle: 'Comment Faire Pendant les Événements',
    eventsDesc: 'Stratégies de gestion des équipements pour maintenir le pouvoir spirituel bas',
    guardWeaponsStrategy: 'Stratégie des Armes de la Garde',
    guardWeaponsContent: 'Gardez le pouvoir spirituel bas pendant les événements:',
    equipStrategically: 'Équipez les Armes de la Garde stratégiquement',
    manageTroops: 'Gérez les formations de troupes (Distanza, Cavalleria, Fanteria)',
    exceptionLeaders: 'Exception pour les chefs Cristian et Rasse',
    curiositiesManagement: 'Gestion des Curiosités',
    optimizeCollection: 'Optimisez votre collection:',
    collectCombine: 'Collectez et combinez les Curiosités',
    trackPowerChanges: 'Suivez les changements du pouvoir spirituel',
    planLoadouts: 'Planifiez des équipements spécifiques aux événements',
    coaNew: 'Blasons (Nouveau)',
    newestFeature: 'La dernière fonctionnalité pour contrôler le pouvoir spirituel:',
    applyCoa: 'Appliquez les Blasons pour des effets bonus',
    calculateImpact: 'Calculez l\'impact combiné du pouvoir spirituel',
    maximizePerformance: 'Maximisez la performance des événements',
    copyright: 'Guns of Glory',
  },
  RU: {
    headerBranding: 'Отлично Сделано! Мы - Чемпионский Регион!!',
    headerSubtitle: 'Теперь давайте попытаемся исправить ошибки, допущенные до того, как будет слишком поздно',
    spiritualPowerTitle: 'Управление Духовной Силой',
    spiritualPowerDesc: 'Узнайте, как управлять духовной силой вашего королевства во время событий',
    guardWeapons: 'Оружие Охраны',
    curiosities: 'Редкости',
    coatsOfArms: 'Гербы',
    newBadge: 'Новое',
    eventsTitle: 'Что Делать Во Время Событий',
    eventsDesc: 'Стратегии управления оружием для поддержания низкой духовной силы',
    guardWeaponsStrategy: 'Стратегия Оружия Охраны',
    guardWeaponsContent: 'Поддерживайте низкую духовную силу во время событий:',
    equipStrategically: 'Оснащайте Оружие Охраны стратегически',
    manageTroops: 'Управляйте формациями войск (Distanza, Cavalleria, Fanteria)',
    exceptionLeaders: 'Исключение для лидеров Cristian и Rasse',
    curiositiesManagement: 'Управление Редкостями',
    optimizeCollection: 'Оптимизируйте вашу коллекцию:',
    collectCombine: 'Собирайте и комбинируйте Редкости',
    trackPowerChanges: 'Отслеживайте изменения духовной силы',
    planLoadouts: 'Планируйте специфические для событий конфигурации',
    coaNew: 'Гербы (Новое)',
    newestFeature: 'Новейшая функция для контроля духовной силы:',
    applyCoa: 'Применяйте Гербы для бонусных эффектов',
    calculateImpact: 'Рассчитайте комбинированное влияние духовной силы',
    maximizePerformance: 'Максимизируйте производительность события',
    copyright: 'Guns of Glory',
  },
  ES: {
    headerBranding: '¡Bien Hecho! ¡Somos la Región Campeona!!',
    headerSubtitle: 'Ahora intentemos recuperarnos de los errores cometidos antes de que sea demasiado tarde',
    spiritualPowerTitle: 'Gestión del Poder Espiritual',
    spiritualPowerDesc: 'Aprende cómo gestionar el poder espiritual de tu reino durante los eventos',
    guardWeapons: 'Armas de la Guardia',
    curiosities: 'Curiosidades',
    coatsOfArms: 'Escudos de Armas',
    newBadge: 'Nuevo',
    eventsTitle: 'Qué Hacer Durante los Eventos',
    eventsDesc: 'Estrategias de gestión de equipos para mantener bajo el poder espiritual',
    guardWeaponsStrategy: 'Estrategia de Armas de la Guardia',
    guardWeaponsContent: 'Mantén el poder espiritual bajo durante los eventos:',
    equipStrategically: 'Equipa Armas de la Guardia estratégicamente',
    manageTroops: 'Gestiona las formaciones de tropas (Distanza, Cavalleria, Fanteria)',
    exceptionLeaders: 'Excepción para los líderes Cristian y Rasse',
    curiositiesManagement: 'Gestión de Curiosidades',
    optimizeCollection: 'Optimiza tu colección:',
    collectCombine: 'Recopila y combina Curiosidades',
    trackPowerChanges: 'Rastrea los cambios del poder espiritual',
    planLoadouts: 'Planifica equipos específicos para eventos',
    coaNew: 'Escudos de Armas (Nuevo)',
    newestFeature: 'La función más nueva para el control del poder espiritual:',
    applyCoa: 'Aplica Escudos de Armas para efectos bonus',
    calculateImpact: 'Calcula el impacto combinado del poder espiritual',
    maximizePerformance: 'Maximiza el rendimiento del evento',
    copyright: 'Guns of Glory',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
