'use client';

import React, { createContext, useContext, useState } from 'react';

type Language = 'EN' | 'IT' | 'PL' | 'ZH' | 'DE' | 'FR' | 'RU' | 'ES';

const translations: Record<Language, Record<string, string>> = {
  EN: {
    headerBranding: 'Well Done! We\'re Champion Region!!',
    projectName: 'k698 - Renaissance Project',
    renaissance: 'RENAISSANCE',
    headerSubtitle: 'Now let\'s try to recover from the mistakes made before it\'s too late',
    spiritualPowerTitle: 'Spiritual Power Management',
    spiritualPowerBanner: 'SPOILER ALERT: This is not advice or a friendly request. This is a rule to follow.',
    spiritualPowerDesc: 'Learn how to manage your kingdom\'s spiritual power during events',
    guardWeapons: 'Guard Weapons',
    curiosities: 'Curiosities',
    coatsOfArms: 'Coats of Arms',
    newBadge: 'New',
    eventsTitle: 'Afraid of not scoring points in events? Now Uncle ReVaN explains how to do it',
    eventsSubtitle: 'It\'s easier than you think...',
    eventsContext: 'During 50% Pirates\' Chest, Limited Royal Expeditions with Coat of Arms, Guard Weapons, and Curiosities missions:',
    eventStep1Title: 'Step 1: Remove Lord Equipment',
    eventStep1Desc: 'Take off your Lord\'s current equipment',
    eventStep2Title: 'Step 2: Remove All Ship Parts',
    eventStep2Desc: 'Remove all ship parts',
    eventStep3Title: 'Step 3: Remount and Enhance All Equipment',
    eventStep3Desc: 'Now you can remount and enhance all types of Guard Weapons, Coats of Arms, and Curiosities based on the daily mission requirements.',
    eventStep4Title: 'Step 4: Remove Superfluous Items',
    eventStep4Desc: 'Strip away unnecessary items to keep spiritual power low',
    eventStep5Title: 'Step 5: Restore Ship and Equipment',
    eventStep5Desc: 'Put back ship parts and Lord equipment',
    guardWeaponsStrategy: 'Guard Weapons Strategy',
    guardWeaponsContent: 'Replace Guard Weapons based on your main troop type:',
    equipStrategically: 'Cavalry: Replace Infantry and Distanza Guard Weapons with level 1-2-3 or 4 weapons',
    manageTroops: 'Distanza: Replace Infantry and Cavalry Guard Weapons with level 1-2-3 or 4 weapons',
    exceptionLeaders: 'Keep optimal weapons to maintain low spiritual power',
    curiositiesManagement: 'Curiosities Management',
    curiositiesContent: 'Replace Curiosities based on your main troop type:',
    collectCombine: 'Cavalry: Replace Infantry and Distanza Curiosities with level 1-2-3 or 4 items',
    trackPowerChanges: 'Distanza: Replace Infantry and Cavalry Curiosities with level 1-2-3 or 4 items',
    planLoadouts: 'Keep optimal Curiosities to maintain low spiritual power',
    coaNew: 'Coats of Arms (R17)',
    newestFeature: 'Replace Coats of Arms with R17 based on your main troop type:',
    applyCoa: 'Cavalry: Replace Infantry and Distanza with R17 Coats of Arms',
    calculateImpact: 'Distanza: Replace Cavalry and Infantry with R17 Coats of Arms',
    maximizePerformance: 'Exception: Rasse and Cristian are excluded from this strategy',
    
    // Leaderboard
    leaderboardTitle: 'Kingdom Leaderboard',
    leaderboardDesc: 'Ranked by Historical Power',
    loginToView: 'Sign in to view the leaderboard',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    refreshLeaderboard: 'Refresh',
    addCastle: '+ Add Castle',
    myAccount: '👤 My Account',
    
    // Leaderboard Table
    rank: 'Rank',
    castleName: 'Castle Name',
    historicalPower: 'Historical Power',
    currentPower: 'Current Power',
    screenshot: 'Screenshot',
    lastUpdated: 'Last Updated',
    
    // Account Sheet
    myKingdom: '👑 My Kingdom',
    nickname: 'Nickname',
    email: 'Email',
    myCastles: '🏰 My Castles',
    settings: '⚙️ Settings',
    changeEmail: 'Change Email',
    changePassword: 'Change Password',
    save: 'Save',
    logout: 'Logout',
    
    // Auth
    emailLabel: 'Email',
    passwordLabel: 'Password',
    nicknameLabel: 'Nickname',
    registerTitle: 'Create Account',
    loginTitle: 'Sign In',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: 'Don\'t have an account?',
    
    // KvK Warning
    kvkWarningTitle: 'KvK Power Update Required',
    kvkWarningMessage: 'Players who do not submit or update their power data will not receive KvK rewards. Regular updates ensure your kingdom is properly ranked and eligible for rewards. Sign in to submit your power data and appear on the leaderboard.',
    
    // Auth Sheet
    myAccount: 'My Account',
    forgotPassword: 'Forgot password?',
    resetPassword: 'Reset password',
    resetPasswordDesc: "Enter your email address and we'll send you a link to reset your password.",
    sendResetLink: 'Send reset link',
    confirmPasswordLabel: 'Confirm password',
    passwordMismatch: 'Passwords do not match',
    loginFailed: 'Login failed',
    registrationFailed: 'Registration failed',
    connectionError: 'Connection error',
    comingSoon: 'Coming soon. Contact support.',
    signOut: 'Sign out',
    updateEmail: 'Update email',
    castlesLabel: 'Castles',
    addCastleBtn: '+ Add castle',
    doneLabel: 'Done',
    signingIn: 'Signing in\u2026',
    creating: 'Creating\u2026',
    sending: 'Sending\u2026',
    openAccount: 'My Account',
    
    copyright: 'Guns of Glory',
  },
  IT: {
    headerBranding: 'Ben Fatto! Siamo in regione campioni!!',
    projectName: 'k698 - Progetto Rinascita',
     renaissance: 'RINASCITA',
    headerSubtitle: 'Ora proviamo a recuperare agli errori commessi prima che sia troppo tardi',
    spiritualPowerTitle: 'Gestione del Potere Spirituale',
    spiritualPowerBanner: 'SPOILER ALERT: Questo non è un consiglio nè una richiesta amichevole. Questa è una regola da seguire.',
    spiritualPowerDesc: 'Impara come gestire il potere spirituale del tuo regno durante gli eventi',
    guardWeapons: 'Armi della Guardia',
    curiosities: 'Curiosità',
    coatsOfArms: 'Stemmi',
    newBadge: 'Novità',
    eventsTitle: 'Paura di non fare punti negli eventi? Ora Zio ReVaN ti spiega come fare',
    eventsSubtitle: 'È più semplice di quello che pensi...',
    eventsContext: 'Durante il 50% Cassa dei Pirati, Spedizioni Reali Limitate con missioni di Stemmi, Armi della Guardia e Curiosità:',
     eventStep1Title: 'Passo 1: Togli Equipaggiamento del Lord',
     eventStep1Desc: 'Togli l\'equipaggiamento attuale del tuo Lord',
     eventStep2Title: 'Passo 2: Togli Tutte le Parti della Nave',
     eventStep2Desc: 'Rimuovi tutte le parti della nave',
     eventStep3Title: 'Passo 3: Rimonta e Potenzia Tutto',
     eventStep3Desc: 'Ora puoi rimontare e potenziare tutti i tipi di Armi della Guardia, Stemmi e Curiosità in base ai requisiti della missione giornaliera.',
    eventStep4Title: 'Passo 4: Togli le Cose Superflue',
    eventStep4Desc: 'Togli gli oggetti non necessari per mantenere il potere spirituale basso',
    eventStep5Title: 'Passo 5: Rimetti Nave ed Equipaggiamento',
    eventStep5Desc: 'Rimetti le parti della nave e l\'equipaggiamento del Lord',
    guardWeaponsStrategy: 'Strategia Armi della Guardia',
    guardWeaponsContent: 'Sostituisci le Armi della Guardia in base al tipo di truppa principale:',
    equipStrategically: 'Cavalleria: Sostituisci Armi della Guardia di Fanteria e Distanza con armi di livello 1-2-3 o 4',
    manageTroops: 'Distanza: Sostituisci Armi della Guardia di Fanteria e Cavalleria con armi di livello 1-2-3 o 4',
    exceptionLeaders: 'Mantieni armi ottimali per mantenere basso il potere spirituale',
    curiositiesManagement: 'Gestione delle Curiosità',
    curiositiesContent: 'Sostituisci le Curiosità in base al tipo di truppa principale:',
    collectCombine: 'Cavalleria: Sostituisci Curiosità di Fanteria e Distanza con oggetti di livello 1-2-3 o 4',
    trackPowerChanges: 'Distanza: Sostituisci Curiosità di Fanteria e Cavalleria con oggetti di livello 1-2-3 o 4',
    planLoadouts: 'Mantieni Curiosità ottimali per mantenere basso il potere spirituale',
     coaNew: 'Stemmi (R17)',
     newestFeature: 'Sostituisci gli Stemmi con R17 in base al tipo di truppa principale:',
     applyCoa: 'Cavalleria: Sostituisci Fanteria e Distanza con Stemmi R17',
     calculateImpact: 'Distanza: Sostituisci Cavalleria e Fanteria con Stemmi R17',
     maximizePerformance: 'Eccezione: Rasse e Cristian sono esclusi da questa strategia',
     
     // Leaderboard
     leaderboardTitle: 'Classifica del Regno',
     leaderboardDesc: 'Ordinato per Potere Storico',
     loginToView: 'Accedi per visualizzare la classifica',
     signIn: 'Accedi',
     signUp: 'Registrati',
     refreshLeaderboard: 'Aggiorna',
     addCastle: '+ Aggiungi Castello',
     myAccount: '👤 Il Mio Account',
     
     // Leaderboard Table
     rank: 'Posizione',
     castleName: 'Nome Castello',
     historicalPower: 'Potere Storico',
     currentPower: 'Potere Attuale',
     screenshot: 'Screenshot',
     lastUpdated: 'Ultimo Aggiornamento',
     
     // Account Sheet
     myKingdom: '👑 Il Mio Regno',
     nickname: 'Nickname',
     email: 'Email',
     myCastles: '🏰 I Miei Castelli',
     settings: '⚙️ Impostazioni',
     changeEmail: 'Cambia Email',
     changePassword: 'Cambia Password',
     save: 'Salva',
     logout: 'Esci',
     
     // Auth
     emailLabel: 'Email',
     passwordLabel: 'Password',
     nicknameLabel: 'Nickname',
     registerTitle: 'Crea Account',
     loginTitle: 'Accedi',
      alreadyHaveAccount: 'Hai già un account?',
      dontHaveAccount: 'Non hai un account?',
      
      // KvK Warning
      kvkWarningTitle: 'Aggiornamento Potere KvK Richiesto',
      kvkWarningMessage: 'I giocatori che non inviano o aggiornano i dati di potere non riceveranno i premi KvK. Gli aggiornamenti regolari garantiscono che il tuo regno sia correttamente classificato e idoneo per i premi. Accedi per inviare i dati di potere e apparire nella classifica.',
      
      // Auth Sheet
      myAccount: 'Il Mio Account',
      forgotPassword: 'Password dimenticata?',
      resetPassword: 'Reimposta password',
      resetPasswordDesc: 'Inserisci la tua email e ti invieremo un link per reimpostare la password.',
      sendResetLink: 'Invia link di reset',
      confirmPasswordLabel: 'Conferma password',
      passwordMismatch: 'Le password non corrispondono',
      loginFailed: 'Accesso fallito',
      registrationFailed: 'Registrazione fallita',
      connectionError: 'Errore di connessione',
      comingSoon: 'Prossimamente. Contatta il supporto.',
      signOut: 'Esci',
      updateEmail: 'Aggiorna email',
      castlesLabel: 'Castelli',
      addCastleBtn: '+ Aggiungi castello',
      doneLabel: 'Fatto',
      signingIn: 'Accesso in corso\u2026',
      creating: 'Creazione\u2026',
      sending: 'Invio\u2026',
      openAccount: 'Il Mio Account',
      
      copyright: 'Guns of Glory',
   },
  PL: {
    headerBranding: 'Świetnie! Jesteśmy Regionem Mistrzów!!',
    projectName: 'k698 - Projekt Odrodzenia',
     renaissance: 'ODRODZENIE',
    headerSubtitle: 'Teraz spróbujmy naprawić błędy popełnione zanim będzie za późno',
    spiritualPowerTitle: 'Zarządzanie Mocą Duchową',
    spiritualPowerBanner: 'SPOILER ALERT: To nie jest porada ani przyjazna prośba. To zasada, którą należy stosować.',
    spiritualPowerDesc: 'Dowiedz się, jak zarządzać mocą duchową swojego królestwa podczas wydarzeń',
    guardWeapons: 'Broń Gwardii',
    curiosities: 'Osobliwości',
    coatsOfArms: 'Herbarze',
    newBadge: 'Nowe',
    eventsTitle: 'Boisz się nie zdobyć punktów na eventach? Teraz Wujek ReVaN wyjaśnia jak to zrobić',
    eventsSubtitle: 'To prostsze niż myślisz...',
    eventsContext: 'Podczas 50% Skarbu Piratów, Ograniczonych Ekspedycji Królewskich z misjami Herbarzy, Broni Gwardii i Osobliwości:',
     eventStep1Title: 'Krok 1: Zdejmij Equipement Lorda',
     eventStep1Desc: 'Zdejmij obecne equipement swojego Lorda',
     eventStep2Title: 'Krok 2: Zdejmij Wszystkie Części Statku',
     eventStep2Desc: 'Usuń wszystkie części statku',
     eventStep3Title: 'Krok 3: Przesuń i Ulepsz Wszystko',
     eventStep3Desc: 'Teraz możesz przesuć i ulepszać wszystkie rodzaje Broni Gwardii, Herbarzy i Osobliwości w oparciu o wymagania dziennej misji.',
    eventStep4Title: 'Krok 4: Zdejmij Niepotrzebne Przedmioty',
    eventStep4Desc: 'Usuń niepotrzebne przedmioty, aby utrzymać niską moc duchową',
    eventStep5Title: 'Krok 5: Przywróć Statek i Equipement',
    eventStep5Desc: 'Załóż z powrotem części statku i equipement Lorda',
    guardWeaponsStrategy: 'Strategia Broni Gwardii',
    guardWeaponsContent: 'Zastąp Bronie Gwardii w zależności od typu głównych wojsk:',
    equipStrategically: 'Kawaleria: Zastąp Bronie Gwardii Piechoty i Dystansu bronią poziomu 1-2-3 lub 4',
    manageTroops: 'Dystans: Zastąp Bronie Gwardii Piechoty i Kawalerii bronią poziomu 1-2-3 lub 4',
    exceptionLeaders: 'Zachowaj optymalne bronie, aby utrzymać niską moc duchową',
    curiositiesManagement: 'Zarządzanie Osobliwościami',
    curiositiesContent: 'Zastąp Osobliwości w zależności od typu głównych wojsk:',
    collectCombine: 'Kawaleria: Zastąp Osobliwości Piechoty i Dystansu przedmiotami poziomu 1-2-3 lub 4',
    trackPowerChanges: 'Dystans: Zastąp Osobliwości Piechoty i Kawalerii przedmiotami poziomu 1-2-3 lub 4',
    planLoadouts: 'Zachowaj optymalne Osobliwości, aby utrzymać niską moc duchową',
     coaNew: 'Herbarze (R17)',
     newestFeature: 'Zastąp Herbarze R17 w zależności od typu głównych wojsk:',
     applyCoa: 'Kawaleria: Zastąp Piechota i Dystans Herbarze R17',
     calculateImpact: 'Dystans: Zastąp Kawaleria i Piechota Herbarze R17',
      maximizePerformance: 'Wyjątek: Rasse i Cristian są wyłączeni z tej strategii',
      
      // Leaderboard
      leaderboardTitle: 'Tablica Liderów Królestwa',
      leaderboardDesc: 'Rankingowany według Mocy Historycznej',
      loginToView: 'Zaloguj się, aby zobaczyć tabelę liderów',
      signIn: 'Zaloguj się',
      signUp: 'Zarejestruj się',
      refreshLeaderboard: 'Odśwież',
      addCastle: '+ Dodaj Zamek',
      myAccount: '👤 Moje Konto',
      
      // Leaderboard Table
      rank: 'Ranking',
      castleName: 'Nazwa Zamku',
      historicalPower: 'Moc Historyczna',
      currentPower: 'Aktualna Moc',
      screenshot: 'Zrzut Ekranu',
      lastUpdated: 'Ostatnia Aktualizacja',
      
      // Account Sheet
      myKingdom: '👑 Moje Królestwo',
      nickname: 'Pseudonim',
      email: 'Email',
      myCastles: '🏰 Moje Zamki',
      settings: '⚙️ Ustawienia',
      changeEmail: 'Zmień Email',
      changePassword: 'Zmień Hasło',
      save: 'Zapisz',
      logout: 'Wyloguj się',
      
      // Auth
      emailLabel: 'Email',
      passwordLabel: 'Hasło',
      nicknameLabel: 'Pseudonim',
      registerTitle: 'Utwórz Konto',
      loginTitle: 'Zaloguj się',
      alreadyHaveAccount: 'Już masz konto?',
      dontHaveAccount: 'Nie masz konta?',
      
      // KvK Warning
      kvkWarningTitle: 'Wymagana Aktualizacja Mocy KvK',
      kvkWarningMessage: 'Gracze, którzy nie przesyłają ani nie aktualizują danych mocy, nie otrzymają nagród KvK. Regularne aktualizacje zapewniają, że twoje królestwo jest prawidłowo sklasyfikowane i uprawnione do nagród. Zaloguj się, aby przesłać dane mocy i pojawić się na liście liderów.',
      
       // Auth Sheet
       myAccount: 'Moje Konto',
       forgotPassword: 'Zapomniałeś hasła?',
       resetPassword: 'Resetuj hasło',
       resetPasswordDesc: 'Podaj swój adres email, a wyślemy Ci link do resetowania hasła.',
       sendResetLink: 'Wyślij link resetujący',
       confirmPasswordLabel: 'Potwierdź hasło',
       passwordMismatch: 'Hasła nie pasują do siebie',
       loginFailed: 'Logowanie nieudane',
       registrationFailed: 'Rejestracja nieudana',
       connectionError: 'Błąd połączenia',
       comingSoon: 'Wkrótce. Skontaktuj się z pomocą.',
       signOut: 'Wyloguj się',
       updateEmail: 'Zaktualizuj email',
       castlesLabel: 'Zamki',
       addCastleBtn: '+ Dodaj zamek',
       doneLabel: 'Gotowe',
       signingIn: 'Logowanie\u2026',
       creating: 'Tworzenie\u2026',
       sending: 'Wysyłanie\u2026',
       openAccount: 'Moje Konto',
       
       copyright: 'Guns of Glory',
       },
  ZH: {
    headerBranding: '做得好！我们是冠军地区！！',
    projectName: 'k698 - 复兴计划',
    headerSubtitle: '现在让我们尝试纠正之前犯下的错误，趁还不晚',
    spiritualPowerTitle: '精神力管理',
    spiritualPowerBanner: '剧透警告: 这不是建议，也不是友好的请求。这是必须遵循的规则。',
    spiritualPowerDesc: '学习如何在事件期间管理您的王国精神力',
    guardWeapons: '护卫武器',
    curiosities: '奇特物品',
    coatsOfArms: '纹章',
    newBadge: '新',
    eventsTitle: '害怕在事件中得不到分数? 现在 Uncle ReVaN 教你怎么做',
    eventsSubtitle: '其实没那么复杂...',
    eventsContext: '在50%海盗宝箱、限制皇家远征（纹章、护卫武器和奇特物品任务）期间:',
     eventStep1Title: '步骤1: 卸下领主装备',
     eventStep1Desc: '卸下你领主的当前装备',
     eventStep2Title: '步骤2: 卸下所有船舶部件',
     eventStep2Desc: '移除所有船舶部件',
     eventStep3Title: '步骤3: 重新装配和增强所有内容',
     eventStep3Desc: '现在您可以根据日常任务要求重新装配和增强所有类型的护卫武器、纹章和奇特物品。',
    eventStep4Title: '步骤4: 卸下多余物品',
    eventStep4Desc: '移除不必要的物品以保持精神力低',
    eventStep5Title: '步骤5: 恢复船舶和装备',
    eventStep5Desc: '装回船舶部件和领主装备',
    guardWeaponsStrategy: '护卫武器策略',
    guardWeaponsContent: '根据您的主要部队类型替换护卫武器:',
    equipStrategically: '骑兵: 用1-2-3或4级武器替换步兵和远程护卫武器',
    manageTroops: '远程: 用1-2-3或4级武器替换步兵和骑兵护卫武器',
    exceptionLeaders: '保持最优武器以保持精神力低',
    curiositiesManagement: '奇特物品管理',
    curiositiesContent: '根据您的主要部队类型替换奇特物品:',
    collectCombine: '骑兵: 用1-2-3或4级物品替换步兵和远程奇特物品',
    trackPowerChanges: '远程: 用1-2-3或4级物品替换步兵和骑兵奇特物品',
    planLoadouts: '保持最优奇特物品以保持精神力低',
     coaNew: '纹章 (R17)',
     newestFeature: '根据您的主要部队类型用R17替换纹章:',
     applyCoa: '骑兵: 用R17纹章替换步兵和远程',
     calculateImpact: '远程: 用R17纹章替换骑兵和步兵',
      maximizePerformance: '例外: Rasse和Cristian被排除在此策略之外',
      
      // Leaderboard
      leaderboardTitle: '王国排行榜',
      leaderboardDesc: '按历史力量排名',
      loginToView: '登录查看排行榜',
      signIn: '登录',
      signUp: '注册',
      refreshLeaderboard: '刷新',
      addCastle: '+ 添加城堡',
      myAccount: '👤 我的账户',
      
      // Leaderboard Table
      rank: '排名',
      castleName: '城堡名称',
      historicalPower: '历史力量',
      currentPower: '当前力量',
      screenshot: '截图',
      lastUpdated: '上次更新',
      
      // Account Sheet
      myKingdom: '👑 我的王国',
      nickname: '昵称',
      email: '邮箱',
      myCastles: '🏰 我的城堡',
      settings: '⚙️ 设置',
      changeEmail: '更改邮箱',
      changePassword: '更改密码',
      save: '保存',
      logout: '登出',
      
      // Auth
      emailLabel: '邮箱',
      passwordLabel: '密码',
      nicknameLabel: '昵称',
      registerTitle: '创建账户',
      loginTitle: '登录',
       alreadyHaveAccount: '已有账户?',
       dontHaveAccount: '没有账户?',
       
       // KvK Warning
       kvkWarningTitle: '需要KvK力量更新',
       kvkWarningMessage: '不提交或更新力量数据的玩家将无法获得KvK奖励。定期更新可确保您的王国正确排名并符合奖励条件。登录以提交力量数据并出现在排行榜上。',
       
        // Auth Sheet
        myAccount: '我的账户',
        forgotPassword: '忘记密码？',
        resetPassword: '重置密码',
        resetPasswordDesc: '输入您的电子邮件地址，我们将向您发送重置密码的链接。',
        sendResetLink: '发送重置链接',
        confirmPasswordLabel: '确认密码',
        passwordMismatch: '密码不匹配',
        loginFailed: '登录失败',
        registrationFailed: '注册失败',
        connectionError: '连接错误',
        comingSoon: '即将推出。请联系支持。',
        signOut: '退出登录',
        updateEmail: '更新邮箱',
        castlesLabel: '城堡',
        addCastleBtn: '+ 添加城堡',
        doneLabel: '完成',
        signingIn: '登录中\u2026',
        creating: '创建中\u2026',
        sending: '发送中\u2026',
        openAccount: '我的账户',
        
        renaissance: '复兴',
        copyright: 'Guns of Glory',
       },
  DE: {
    headerBranding: 'Gut Gemacht! Wir Sind Championregion!!',
    projectName: 'k698 - Wiedergeburtsprojekt',
     renaissance: 'WIEDERGEBURT',
    headerSubtitle: 'Jetzt versuchen wir, die Fehler zu beheben, bevor es zu spät ist',
    spiritualPowerTitle: 'Verwaltung der Spirituellen Kraft',
    spiritualPowerBanner: 'SPOILER ALERT: Dies ist kein Ratschlag und keine freundliche Bitte. Das ist eine Regel, die man befolgen muss.',
    spiritualPowerDesc: 'Lerne, wie du die spirituelle Kraft deines Königreichs während Events verwaltest',
    guardWeapons: 'Wachausrüstung',
    curiosities: 'Kuriositäten',
    coatsOfArms: 'Wappen',
    newBadge: 'Neu',
    eventsTitle: 'Angst, in Events keine Punkte zu machen? Jetzt erklärt dir Onkel ReVaN, wie man es macht',
    eventsSubtitle: 'Es ist einfacher als du denkst...',
    eventsContext: 'Während 50% Piratenkasse, Begrenzte Königliche Expeditionen mit Wappen-, Wachausrüstungs- und Kuriositätsmissionen:',
     eventStep1Title: 'Schritt 1: Lord-Ausrüstung ablegen',
     eventStep1Desc: 'Nimm die aktuelle Ausrüstung deines Lords ab',
     eventStep2Title: 'Schritt 2: Alle Schiffsteile entfernen',
     eventStep2Desc: 'Entferne alle Schiffsteile',
     eventStep3Title: 'Schritt 3: Alles Neu Montieren und Verbessern',
     eventStep3Desc: 'Jetzt können Sie alle Arten von Wachausrüstung, Wappen und Kuriositäten basierend auf den täglichen Missionsanforderungen neu montieren und verbessern.',
    eventStep4Title: 'Schritt 4: Unnötige Gegenstände entfernen',
    eventStep4Desc: 'Entferne unnötige Gegenstände, um die spirituelle Kraft niedrig zu halten',
    eventStep5Title: 'Schritt 5: Schiff und Ausrüstung wiederherstellen',
    eventStep5Desc: 'Lege Schiffsteile und Lord-Ausrüstung zurück',
    guardWeaponsStrategy: 'Wachausrüstungsstrategie',
    guardWeaponsContent: 'Ersetzen Sie Wachausrüstung basierend auf Ihrem Haupttruppentyp:',
    equipStrategically: 'Kavallerie: Ersetzen Sie Infanterie- und Distanz-Wachausrüstung durch Waffen der Stufe 1-2-3 oder 4',
    manageTroops: 'Distanz: Ersetzen Sie Infanterie- und Kavallerie-Wachausrüstung durch Waffen der Stufe 1-2-3 oder 4',
    exceptionLeaders: 'Behalten Sie optimale Waffen, um die spirituelle Kraft niedrig zu halten',
    curiositiesManagement: 'Kuriositätenverwaltung',
    curiositiesContent: 'Ersetzen Sie Kuriositäten basierend auf Ihrem Haupttruppentyp:',
    collectCombine: 'Kavallerie: Ersetzen Sie Infanterie- und Distanz-Kuriositäten durch Gegenstände der Stufe 1-2-3 oder 4',
    trackPowerChanges: 'Distanz: Ersetzen Sie Infanterie- und Kavallerie-Kuriositäten durch Gegenstände der Stufe 1-2-3 oder 4',
    planLoadouts: 'Behalten Sie optimale Kuriositäten, um die spirituelle Kraft niedrig zu halten',
     coaNew: 'Wappen (R17)',
     newestFeature: 'Ersetzen Sie Wappen mit R17 basierend auf Ihrem Haupttruppentyp:',
     applyCoa: 'Kavallerie: Ersetzen Sie Infanterie und Distanz mit R17 Wappen',
     calculateImpact: 'Distanz: Ersetzen Sie Kavallerie und Infanterie mit R17 Wappen',
      maximizePerformance: 'Ausnahme: Rasse und Cristian sind von dieser Strategie ausgeschlossen',
      
      // Leaderboard
      leaderboardTitle: 'Königreich Rangliste',
      leaderboardDesc: 'Nach Historischer Kraft geordnet',
      loginToView: 'Melden Sie sich an, um die Rangliste anzuzeigen',
      signIn: 'Anmelden',
      signUp: 'Registrieren',
      refreshLeaderboard: 'Aktualisieren',
      addCastle: '+ Schloss hinzufügen',
      myAccount: '👤 Mein Konto',
      
      // Leaderboard Table
      rank: 'Rang',
      castleName: 'Schlossname',
      historicalPower: 'Historische Kraft',
      currentPower: 'Aktuelle Kraft',
      screenshot: 'Screenshot',
      lastUpdated: 'Zuletzt aktualisiert',
      
      // Account Sheet
      myKingdom: '👑 Mein Königreich',
      nickname: 'Spitzname',
      email: 'E-Mail',
      myCastles: '🏰 Meine Schlösser',
      settings: '⚙️ Einstellungen',
      changeEmail: 'E-Mail ändern',
      changePassword: 'Passwort ändern',
      save: 'Speichern',
      logout: 'Abmelden',
      
      // Auth
      emailLabel: 'E-Mail',
      passwordLabel: 'Passwort',
      nicknameLabel: 'Spitzname',
      registerTitle: 'Konto erstellen',
      loginTitle: 'Anmelden',
       alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
        dontHaveAccount: 'Sie haben kein Konto?',
        
        // KvK Warning
        kvkWarningTitle: 'KvK-Kraftaktualisierung erforderlich',
        kvkWarningMessage: 'Spieler, die ihre Kraftdaten nicht einreichen oder aktualisieren, erhalten keine KvK-Belohnungen. Regelmäßige Aktualisierungen stellen sicher, dass Ihr Königreich ordnungsgemäß eingestuft und für Belohnungen berechtigt ist. Melden Sie sich an, um Kraftdaten einzureichen und in der Rangliste zu erscheinen.',
        
         // Auth Sheet
         myAccount: 'Mein Konto',
         forgotPassword: 'Passwort vergessen?',
         resetPassword: 'Passwort zurücksetzen',
         resetPasswordDesc: 'Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link zum Zurücksetzen.',
         sendResetLink: 'Reset-Link senden',
         confirmPasswordLabel: 'Passwort bestätigen',
         passwordMismatch: 'Passwörter stimmen nicht überein',
         loginFailed: 'Anmeldung fehlgeschlagen',
         registrationFailed: 'Registrierung fehlgeschlagen',
         connectionError: 'Verbindungsfehler',
         comingSoon: 'Bald verfügbar. Support kontaktieren.',
         signOut: 'Abmelden',
         updateEmail: 'E-Mail aktualisieren',
         castlesLabel: 'Schlösser',
         addCastleBtn: '+ Schloss hinzufügen',
         doneLabel: 'Fertig',
         signingIn: 'Anmelden\u2026',
         creating: 'Erstellen\u2026',
         sending: 'Senden\u2026',
         openAccount: 'Mein Konto',
         
         copyright: 'Guns of Glory',
        },
   FR: {
    headerBranding: 'Bien Fait! Nous Sommes Région Championne!!',
    projectName: 'k698 - Projet Renaissance',
     renaissance: 'RENAISSANCE',
    headerSubtitle: 'Maintenant, essayons de corriger les erreurs commises avant qu\'il ne soit trop tard',
    spiritualPowerTitle: 'Gestion du Pouvoir Spirituel',
    spiritualPowerBanner: 'SPOILER ALERT: Ce n\'est pas un conseil, ni une demande amicale. C\'est une règle à suivre.',
    spiritualPowerDesc: 'Apprenez à gérer le pouvoir spirituel de votre royaume pendant les événements',
    guardWeapons: 'Armes de la Garde',
    curiosities: 'Curiosités',
    coatsOfArms: 'Blasons',
    newBadge: 'Nouveau',
    eventsTitle: 'Peur de ne pas scorer aux événements? Maintenant Oncle ReVaN t\'explique comment faire',
    eventsSubtitle: 'C\'est plus simple que tu le penses...',
    eventsContext: 'Pendant 50% Trésor des Pirates, Expéditions Royales Limitées avec missions de Blasons, Armes de la Garde et Curiosités:',
     eventStep1Title: 'Étape 1: Retirez l\'équipement du Seigneur',
     eventStep1Desc: 'Retirez l\'équipement actuel de votre Seigneur',
     eventStep2Title: 'Étape 2: Retirez toutes les pièces du navire',
     eventStep2Desc: 'Supprimez toutes les pièces du navire',
     eventStep3Title: 'Étape 3: Remontez et Améliorez Tout',
     eventStep3Desc: 'Vous pouvez maintenant remonter et améliorer tous les types d\'Armes de la Garde, de Blasons et de Curiosités en fonction des exigences de la mission quotidienne.',
    eventStep4Title: 'Étape 4: Supprimez les éléments superflus',
    eventStep4Desc: 'Supprimez les articles inutiles pour maintenir le pouvoir spirituel bas',
    eventStep5Title: 'Étape 5: Restaurez le navire et l\'équipement',
    eventStep5Desc: 'Remettez les pièces du navire et l\'équipement du Seigneur',
    guardWeaponsStrategy: 'Stratégie des Armes de la Garde',
    guardWeaponsContent: 'Remplacez les Armes de la Garde selon votre type de troupes principales:',
    equipStrategically: 'Cavalerie: Remplacez les Armes de la Garde d\'Infanterie et Distanza par des armes de niveau 1-2-3 ou 4',
    manageTroops: 'Distanza: Remplacez les Armes de la Garde d\'Infanterie et Cavalerie par des armes de niveau 1-2-3 ou 4',
    exceptionLeaders: 'Conservez les armes optimales pour maintenir le pouvoir spirituel bas',
    curiositiesManagement: 'Gestion des Curiosités',
    curiositiesContent: 'Remplacez les Curiosités selon votre type de troupes principales:',
    collectCombine: 'Cavalerie: Remplacez les Curiosités d\'Infanterie et Distanza par des objets de niveau 1-2-3 ou 4',
    trackPowerChanges: 'Distanza: Remplacez les Curiosités d\'Infanterie et Cavalerie par des objets de niveau 1-2-3 ou 4',
    planLoadouts: 'Conservez les Curiosités optimales pour maintenir le pouvoir spirituel bas',
     coaNew: 'Blasons (R17)',
     newestFeature: 'Remplacez les Blasons par R17 selon votre type de troupes principales:',
     applyCoa: 'Cavalerie: Remplacez Infanterie et Distanza par Blasons R17',
     calculateImpact: 'Distanza: Remplacez Cavalerie et Infanterie par Blasons R17',
      maximizePerformance: 'Exception: Rasse et Cristian sont exclus de cette stratégie',
      
      // Leaderboard
      leaderboardTitle: 'Classement du Royaume',
      leaderboardDesc: 'Classé par Pouvoir Historique',
      loginToView: 'Connectez-vous pour voir le classement',
      signIn: 'Se Connecter',
      signUp: 'S\'inscrire',
      refreshLeaderboard: 'Actualiser',
      addCastle: '+ Ajouter un Château',
      myAccount: '👤 Mon Compte',
      
      // Leaderboard Table
      rank: 'Classement',
      castleName: 'Nom du Château',
      historicalPower: 'Pouvoir Historique',
      currentPower: 'Pouvoir Actuel',
      screenshot: 'Capture d\'écran',
      lastUpdated: 'Dernière mise à jour',
      
      // Account Sheet
      myKingdom: '👑 Mon Royaume',
      nickname: 'Surnom',
      email: 'E-mail',
      myCastles: '🏰 Mes Châteaux',
      settings: '⚙️ Paramètres',
      changeEmail: 'Modifier E-mail',
      changePassword: 'Modifier Mot de passe',
      save: 'Enregistrer',
      logout: 'Déconnexion',
      
      // Auth
      emailLabel: 'E-mail',
      passwordLabel: 'Mot de passe',
      nicknameLabel: 'Surnom',
      registerTitle: 'Créer un compte',
      loginTitle: 'Se Connecter',
      alreadyHaveAccount: 'Vous avez déjà un compte?',
       dontHaveAccount: 'Vous n\'avez pas de compte?',
       
       // KvK Warning
       kvkWarningTitle: 'Mise à jour de la puissance KvK requise',
       kvkWarningMessage: 'Les joueurs qui ne soumettent pas ou ne mettent pas à jour leurs données de puissance ne recevront pas de récompenses KvK. Les mises à jour régulières garantissent que votre royaume est correctement classé et admissible aux récompenses. Connectez-vous pour soumettre vos données de puissance et apparaître au classement.',
       
        // Auth Sheet
        myAccount: 'Mon Compte',
        forgotPassword: 'Mot de passe oublié?',
        resetPassword: 'Réinitialiser le mot de passe',
        resetPasswordDesc: 'Entrez votre adresse email et nous vous enverrons un lien de réinitialisation.',
        sendResetLink: 'Envoyer le lien de réinitialisation',
        confirmPasswordLabel: 'Confirmer le mot de passe',
        passwordMismatch: 'Les mots de passe ne correspondent pas',
        loginFailed: 'Connexion échouée',
        registrationFailed: 'Inscription échouée',
        connectionError: 'Erreur de connexion',
        comingSoon: 'Bientôt disponible. Contactez le support.',
        signOut: 'Se déconnecter',
        updateEmail: 'Mettre à jour l\'email',
        castlesLabel: 'Châteaux',
        addCastleBtn: '+ Ajouter un château',
        doneLabel: 'Terminé',
        signingIn: 'Connexion\u2026',
        creating: 'Création\u2026',
        sending: 'Envoi\u2026',
        openAccount: 'Mon Compte',
        
        copyright: 'Guns of Glory',
        },
    RU: {
    headerBranding: 'Отлично Сделано! Мы - Чемпионский Регион!!',
    projectName: 'k698 - Проект Возрождения',
    headerSubtitle: 'Теперь давайте попытаемся исправить ошибки, допущенные до того, как будет слишком поздно',
    spiritualPowerTitle: 'Управление Духовной Силой',
    spiritualPowerBanner: 'ВНИМАНИЕ СПОЙЛЕР: Это не совет и не дружеская просьба. Это правило, которое необходимо соблюдать.',
    spiritualPowerDesc: 'Узнайте, как управлять духовной силой вашего королевства во время событий',
    guardWeapons: 'Оружие Охраны',
    curiosities: 'Редкости',
    coatsOfArms: 'Гербы',
    newBadge: 'Новое',
    eventsTitle: 'Боишься не получить очки на событиях? Теперь Дядя ReVaN объясняет как это сделать',
    eventsSubtitle: 'Это проще, чем ты думаешь...',
    eventsContext: 'Во время 50% Сундука Пиратов, Ограниченных Королевских Экспедиций с миссиями Гербов, Оружия Охраны и Редкостей:',
     eventStep1Title: 'Шаг 1: Снимите оружие Лорда',
     eventStep1Desc: 'Снимите текущее оружие вашего Лорда',
     eventStep2Title: 'Шаг 2: Снимите все части корабля',
     eventStep2Desc: 'Удалите все части корабля',
     eventStep3Title: 'Шаг 3: Переустановите и Усилите Все',
     eventStep3Desc: 'Теперь вы можете переустановить и усилить все виды Оружия Охраны, Гербов и Редкостей в зависимости от требований ежедневной миссии.',
    eventStep4Title: 'Шаг 4: Снимите лишние предметы',
    eventStep4Desc: 'Удалите ненужные предметы, чтобы поддерживать низкую духовную силу',
    eventStep5Title: 'Шаг 5: Восстановите корабль и оружие',
    eventStep5Desc: 'Надевайте обратно части корабля и оружие Лорда',
    guardWeaponsStrategy: 'Стратегия Оружия Охраны',
    guardWeaponsContent: 'Замените Оружие Охраны в зависимости от типа основных войск:',
    equipStrategically: 'Кавалерия: Замените Оружие Охраны Пехоты и Дальних на оружие уровня 1-2-3 или 4',
    manageTroops: 'Дальние: Замените Оружие Охраны Пехоты и Кавалерии на оружие уровня 1-2-3 или 4',
    exceptionLeaders: 'Сохраняйте оптимальное оружие, чтобы поддерживать низкую духовную силу',
    curiositiesManagement: 'Управление Редкостями',
    curiositiesContent: 'Замените Редкости в зависимости от типа основных войск:',
    collectCombine: 'Кавалерия: Замените Редкости Пехоты и Дальних на предметы уровня 1-2-3 или 4',
    trackPowerChanges: 'Дальние: Замените Редкости Пехоты и Кавалерии на предметы уровня 1-2-3 или 4',
    planLoadouts: 'Сохраняйте оптимальные Редкости, чтобы поддерживать низкую духовную силу',
     coaNew: 'Гербы (R17)',
     newestFeature: 'Замените Гербы на R17 в зависимости от типа ваших основных войск:',
     applyCoa: 'Кавалерия: Замените Пехоту и Дальних на Гербы R17',
     calculateImpact: 'Дальние: Замените Кавалерию и Пехоту на Гербы R17',
      maximizePerformance: 'Исключение: Rasse и Cristian исключены из этой стратегии',
      
      // Leaderboard
      leaderboardTitle: 'Рейтинг Королевства',
      leaderboardDesc: 'Ранжировано по Исторической Силе',
      loginToView: 'Войдите, чтобы просмотреть рейтинг',
      signIn: 'Вход',
      signUp: 'Регистрация',
      refreshLeaderboard: 'Обновить',
      addCastle: '+ Добавить Замок',
      myAccount: '👤 Мой Аккаунт',
      
      // Leaderboard Table
      rank: 'Рейтинг',
      castleName: 'Название Замка',
      historicalPower: 'Историческая Сила',
      currentPower: 'Текущая Сила',
      screenshot: 'Снимок экрана',
      lastUpdated: 'Последнее обновление',
      
      // Account Sheet
      myKingdom: '👑 Мое Королевство',
      nickname: 'Прозвище',
      email: 'Электронная почта',
      myCastles: '🏰 Мои Замки',
      settings: '⚙️ Настройки',
      changeEmail: 'Изменить Email',
      changePassword: 'Изменить Пароль',
      save: 'Сохранить',
      logout: 'Выход',
      
      // Auth
      emailLabel: 'Электронная почта',
      passwordLabel: 'Пароль',
      nicknameLabel: 'Прозвище',
      registerTitle: 'Создать аккаунт',
      loginTitle: 'Вход',
       alreadyHaveAccount: 'Уже есть аккаунт?',
       dontHaveAccount: 'Нет аккаунта?',
       
       // KvK Warning
       kvkWarningTitle: 'Требуется обновление мощи KvK',
       kvkWarningMessage: 'Игроки, которые не отправляют или не обновляют данные мощи, не получат награды KvK. Регулярные обновления обеспечивают правильную классификацию вашего королевства и его право на получение награды. Войдите, чтобы отправить данные мощи и появиться в рейтинге.',
       
        // Auth Sheet
        myAccount: 'Мой Аккаунт',
        forgotPassword: 'Забыли пароль?',
        resetPassword: 'Сброс пароля',
        resetPasswordDesc: 'Введите ваш email и мы отправим вам ссылку для сброса пароля.',
        sendResetLink: 'Отправить ссылку сброса',
        confirmPasswordLabel: 'Подтвердите пароль',
        passwordMismatch: 'Пароли не совпадают',
        loginFailed: 'Ошибка входа',
        registrationFailed: 'Ошибка регистрации',
        connectionError: 'Ошибка соединения',
        comingSoon: 'Скоро. Обратитесь в поддержку.',
        signOut: 'Выйти',
        updateEmail: 'Обновить email',
        castlesLabel: 'Замки',
        addCastleBtn: '+ Добавить замок',
        doneLabel: 'Готово',
        signingIn: 'Вход\u2026',
        creating: 'Создание\u2026',
        sending: 'Отправка\u2026',
        openAccount: 'Мой Аккаунт',
        
        renaissance: 'ВОЗРОЖДЕНИЕ',
        copyright: 'Guns of Glory',
       },
   ES: {
    headerBranding: '¡Bien Hecho! ¡Somos la Región Campeona!!',
    projectName: 'k698 - Proyecto Renacimiento',
     renaissance: 'RENACIMIENTO',
    headerSubtitle: 'Ahora intentemos recuperarnos de los errores cometidos antes de que sea demasiado tarde',
    spiritualPowerTitle: 'Gestión del Poder Espiritual',
    spiritualPowerBanner: 'ALERTA DE SPOILER: Esto no es un consejo, ni una solicitud amistosa. Es una regla que debe seguirse.',
    spiritualPowerDesc: 'Aprende cómo gestionar el poder espiritual de tu reino durante los eventos',
    guardWeapons: 'Armas de la Guardia',
    curiosities: 'Curiosidades',
    coatsOfArms: 'Escudos de Armas',
    newBadge: 'Nuevo',
    eventsTitle: '¿Miedo de no anotar puntos en los eventos? Ahora Tío ReVaN te explica cómo hacerlo',
    eventsSubtitle: 'Es más simple de lo que crees...',
    eventsContext: 'Durante 50% Cofre de Piratas, Expediciones Reales Limitadas con misiones de Escudos de Armas, Armas de la Guardia y Curiosidades:',
     eventStep1Title: 'Paso 1: Quita el equipamiento del Señor',
     eventStep1Desc: 'Retira el equipamiento actual de tu Señor',
     eventStep2Title: 'Paso 2: Quita todas las partes del barco',
     eventStep2Desc: 'Elimina todas las partes del barco',
     eventStep3Title: 'Paso 3: Remonta y Mejora Todo',
     eventStep3Desc: 'Ahora puedes remontar y mejorar todos los tipos de Armas de la Guardia, Escudos de Armas y Curiosidades según los requisitos de la misión diaria.',
    eventStep4Title: 'Paso 4: Quita las cosas superfluas',
    eventStep4Desc: 'Elimina los artículos innecesarios para mantener el poder espiritual bajo',
    eventStep5Title: 'Paso 5: Restaura el barco y el equipamiento',
    eventStep5Desc: 'Vuelve a poner las partes del barco y el equipamiento del Señor',
    guardWeaponsStrategy: 'Estrategia de Armas de la Guardia',
    guardWeaponsContent: 'Reemplaza las Armas de la Guardia según tu tipo de tropas principales:',
    equipStrategically: 'Caballería: Reemplaza las Armas de la Guardia de Infantería y Distancia con armas de nivel 1-2-3 o 4',
    manageTroops: 'Distancia: Reemplaza las Armas de la Guardia de Infantería y Caballería con armas de nivel 1-2-3 o 4',
    exceptionLeaders: 'Mantén las armas óptimas para mantener bajo el poder espiritual',
    curiositiesManagement: 'Gestión de Curiosidades',
    curiositiesContent: 'Reemplaza las Curiosidades según tu tipo de tropas principales:',
    collectCombine: 'Caballería: Reemplaza las Curiosidades de Infantería y Distancia con objetos de nivel 1-2-3 o 4',
    trackPowerChanges: 'Distancia: Reemplaza las Curiosidades de Infantería y Caballería con objetos de nivel 1-2-3 o 4',
    planLoadouts: 'Mantén las Curiosidades óptimas para mantener bajo el poder espiritual',
     coaNew: 'Escudos de Armas (R17)',
     newestFeature: 'Reemplaza los Escudos de Armas con R17 según tu tipo de tropas principales:',
     applyCoa: 'Caballería: Reemplaza Infantería y Distancia con Escudos de Armas R17',
     calculateImpact: 'Distancia: Reemplaza Caballería e Infantería con Escudos de Armas R17',
      maximizePerformance: 'Excepción: Rasse y Cristian están excluidos de esta estrategia',
      
      // Leaderboard
      leaderboardTitle: 'Tabla de Clasificación del Reino',
      leaderboardDesc: 'Clasificado por Poder Histórico',
      loginToView: 'Inicia sesión para ver la tabla de clasificación',
      signIn: 'Iniciar Sesión',
      signUp: 'Registrarse',
      refreshLeaderboard: 'Actualizar',
      addCastle: '+ Añadir Castillo',
      myAccount: '👤 Mi Cuenta',
      
      // Leaderboard Table
      rank: 'Clasificación',
      castleName: 'Nombre del Castillo',
      historicalPower: 'Poder Histórico',
      currentPower: 'Poder Actual',
      screenshot: 'Captura de pantalla',
      lastUpdated: 'Última actualización',
      
      // Account Sheet
      myKingdom: '👑 Mi Reino',
      nickname: 'Apodo',
      email: 'Correo electrónico',
      myCastles: '🏰 Mis Castillos',
      settings: '⚙️ Configuración',
      changeEmail: 'Cambiar Correo',
      changePassword: 'Cambiar Contraseña',
      save: 'Guardar',
      logout: 'Cerrar Sesión',
      
      // Auth
      emailLabel: 'Correo electrónico',
      passwordLabel: 'Contraseña',
      nicknameLabel: 'Apodo',
      registerTitle: 'Crear Cuenta',
      loginTitle: 'Iniciar Sesión',
      alreadyHaveAccount: '¿Ya tienes una cuenta?',
       dontHaveAccount: '¿No tienes una cuenta?',
       
       // KvK Warning
       kvkWarningTitle: 'Se requiere actualización de poder KvK',
       kvkWarningMessage: 'Los jugadores que no envíen ni actualicen sus datos de poder no recibirán recompensas KvK. Las actualizaciones regulares garantizan que tu reino esté correctamente clasificado y sea elegible para recompensas. Inicia sesión para enviar tus datos de poder y aparecer en el ranking.',
       
        // Auth Sheet
        myAccount: 'Mi Cuenta',
        forgotPassword: '¿Olvidaste la contraseña?',
        resetPassword: 'Restablecer contraseña',
        resetPasswordDesc: 'Ingresa tu dirección de email y te enviaremos un enlace para restablecer.',
        sendResetLink: 'Enviar enlace de restablecimiento',
        confirmPasswordLabel: 'Confirmar contraseña',
        passwordMismatch: 'Las contraseñas no coinciden',
        loginFailed: 'Error de inicio de sesión',
        registrationFailed: 'Error de registro',
        connectionError: 'Error de conexión',
        comingSoon: 'Próximamente. Contacta soporte.',
        signOut: 'Cerrar sesión',
        updateEmail: 'Actualizar email',
        castlesLabel: 'Castillos',
        addCastleBtn: '+ Agregar castillo',
        doneLabel: 'Listo',
        signingIn: 'Iniciando sesión\u2026',
        creating: 'Creando\u2026',
        sending: 'Enviando\u2026',
        openAccount: 'Mi Cuenta',
        
        copyright: 'Guns of Glory',
        },
  };

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
