'use client';

import React, { createContext, useContext, useState } from 'react';

type Language = 'EN' | 'IT' | 'PL' | 'ZH' | 'DE' | 'FR' | 'RU' | 'ES';

const translations: Record<Language, Record<string, string>> = {
  EN: {
    headerBranding: 'Well Done! We\'re Champion Region!!',
    projectName: 'k698 - Renaissance Project',
    headerSubtitle: 'Now let\'s try to recover from the mistakes made before it\'s too late',
    spiritualPowerTitle: 'Spiritual Power Management',
    spiritualPowerBanner: 'SPOILER ALERT: This is not advice or a friendly request. This is a rule to follow.',
    spiritualPowerDesc: 'Learn how to manage your kingdom\'s spiritual power during events',
    guardWeapons: 'Guard Weapons',
    curiosities: 'Curiosities',
    coatsOfArms: 'Coats of Arms',
    newBadge: 'New',
    eventsTitle: 'What To Do During Events',
    eventsSubtitle: 'Afraid of not scoring points in events? Now Uncle ReVaN explains how to do it',
    eventsDesc: 'Equipment management strategies for keeping spiritual power low',
    guardWeaponsStrategy: 'Guard Weapons Strategy',
    guardWeaponsContent: 'Replace Guard Weapons based on your main troop type:',
    equipStrategically: 'Cavalry: Replace Infantry and Distanza Guard Weapons with level 1-2-3 or 4 weapons',
    manageTroops: 'Distanza: Replace Infantry and Cavalry Guard Weapons with level 1-2-3 or 4 weapons',
    exceptionLeaders: 'Keep optimal weapons to maintain low spiritual power',
    curiositiesManagement: 'Curiosities Management',
    curiositiesContent: 'Replace Curiosities based on your main troop type:',
    collectCombine: 'Cavalry: Replace Infantry and Distanza Curiosities with level 1-2-3 or 4 items',
    trackPowerChanges: 'Distanza: Replace Infantry and Cavalry Curiosities with level 1-2-3 or 4 items',
    planLoadouts: 'Keep optimal Curiosities to maintain low spiritual power',
    coaNew: 'Coats of Arms (New)',
    newestFeature: 'Replace Coats of Arms based on your main troop type with R17:',
    applyCoa: 'Infantry and Cavalry: Replace with R17 Coats of Arms for lower spiritual power',
    calculateImpact: 'Distanza: Replace with R17 Coats of Arms',
    maximizePerformance: 'Exception: Rasse and Cristian are excluded from this strategy',
    copyright: 'Guns of Glory',
  },
  IT: {
    headerBranding: 'Ben Fatto! Siamo in regione campioni!!',
    projectName: 'k698 - Progetto Rinascita',
    headerSubtitle: 'Ora proviamo a recuperare agli errori commessi prima che sia troppo tardi',
    spiritualPowerTitle: 'Gestione del Potere Spirituale',
    spiritualPowerBanner: 'SPOILER ALERT: Questo non è un consiglio nè una richiesta amichevole. Questa è una regola da seguire.',
    spiritualPowerDesc: 'Impara come gestire il potere spirituale del tuo regno durante gli eventi',
    guardWeapons: 'Armi della Guardia',
    curiosities: 'Curiosità',
    coatsOfArms: 'Stemmi',
    newBadge: 'Novità',
    eventsTitle: 'Paura di non fare punti negli eventi?',
    eventsSubtitle: 'Ora Zio ReVaN ti spiega come fare',
    eventsDesc: 'Strategie di gestione degli equipaggiamenti per mantenere basso il potere spirituale',
    guardWeaponsStrategy: 'Strategia Armi della Guardia',
    guardWeaponsContent: 'Sostituisci le Armi della Guardia in base al tipo di truppa principale:',
    equipStrategically: 'Cavalleria: Sostituisci Armi della Guardia di Fanteria e Distanza con armi di livello 1-2-3 o 4',
    manageTroops: 'Distanza: Sostituisci Armi della Guardia di Fanteria e Cavalleria con armi di livello 1-2-3 o 4',
    exceptionLeaders: 'Mantieni armi ottimali per mantenere basso il potere spirituale',
    curiositiesManagement: 'Gestione delle Curiosità',
    curiositiesContent: 'Sostituisci le Curiosità in base al tipo di truppa principale:',
    collectCombine: 'Cavalleria: Sostituisci Curiosità di Fanteria e Distanza con oggetti di livello 1-2-3 o 4',
    trackPowerChanges: 'Distanza: Sostituisci Curiosità di Fanteria e Cavalleria con oggetti di livello 1-2-3 o 4',
    planLoadouts: 'Mantieni Curiosità ottimali per mantenere basso il potere spirituale',
     coaNew: 'Stemmi (Novità)',
     newestFeature: 'Sostituisci gli Stemmi in base al tipo di truppa principale con R17:',
     applyCoa: 'Fanteria e Cavalleria: Sostituisci con Stemmi R17 per potere spirituale inferiore',
     calculateImpact: 'Distanza: Sostituisci con Stemmi R17',
     maximizePerformance: 'Eccezione: Rasse e Cristian sono esclusi da questa strategia',
    copyright: 'Guns of Glory',
  },
  PL: {
    headerBranding: 'Świetnie! Jesteśmy Regionem Mistrzów!!',
    projectName: 'k698 - Projekt Odrodzenia',
    headerSubtitle: 'Teraz spróbujmy naprawić błędy popełnione zanim będzie za późno',
    spiritualPowerTitle: 'Zarządzanie Mocą Duchową',
    spiritualPowerBanner: 'SPOILER ALERT: To nie jest porada ani przyjazna prośba. To zasada, którą należy stosować.',
    spiritualPowerDesc: 'Dowiedz się, jak zarządzać mocą duchową swojego królestwa podczas wydarzeń',
    guardWeapons: 'Broń Gwardii',
    curiosities: 'Osobliwości',
    coatsOfArms: 'Herbarze',
    newBadge: 'Nowe',
    eventsTitle: 'Boisz się nie zdobyć punktów na eventach?',
    eventsSubtitle: 'Teraz Wujek ReVaN wyjaśnia jak to zrobić',
    eventsDesc: 'Strategie zarządzania uzbrojeniem aby utrzymać niską moc duchową',
    guardWeaponsStrategy: 'Strategia Broni Gwardii',
    guardWeaponsContent: 'Zastąp Bronie Gwardii w zależności od typu głównych wojsk:',
    equipStrategically: 'Kawaleria: Zastąp Bronie Gwardii Piechoty i Dystansu bronią poziomu 1-2-3 lub 4',
    manageTroops: 'Dystans: Zastąp Bronie Gwardii Piechoty i Kawalerii bronią poziomu 1-2-3 lub 4',
    exceptionLeaders: 'Zachowaj optymalne bronie, aby utrzymać niską moc duchową',
    curiositiesManagement: 'Zarządzanie Osobliwościami',
    curiositiesContent: 'Zastąp Osobliwości w zależności od typu głównych wojsk:',
    collectCombine: 'Kawaleria: Zastąp Osobliwości Piechoty i Dystansu przedmiotami poziomu 1-2-3 lub 4',
    trackPowerChanges: 'Dystans: Zastąp Osobliwości Piechoty i Kawalerii przedmiotami poziomu 1-2-3 lub 4',
    planLoadouts: 'Zachowaj optymalne Osobliwości, aby utrzymać niską moc duchową',
     coaNew: 'Herbarze (Nowe)',
     newestFeature: 'Zastąp Herbarze w zależności od typu głównych wojsk z R17:',
     applyCoa: 'Piechota i Kawaleria: Zastąp Herbarze R17 dla niższej mocy duchowej',
     calculateImpact: 'Dystans: Zastąp Herbarze R17',
     maximizePerformance: 'Wyjątek: Rasse i Cristian są wyłączeni z tej strategii',
    copyright: 'Guns of Glory',
  },
  ZH: {
    headerBranding: '做得好！我们是冠军地区！！',
    projectName: 'k698 - 复兴计划',
    headerSubtitle: '现在让我们尝试纠正之前犯下的错误，趁还不晚',
    spiritualPowerTitle: '精神力管理',
    spiritualPowerBanner: '剧透警告: 这不是建议，也不是友好的请求。这是必须遵循的规则。',
    spiritualPowerDesc: '学习如何在事件期间管理您的王国精神力',
    guardWeapons: '护卫武器',
    curiosities: '奇特物品',
    coatsOfArms: '纹章',
    newBadge: '新',
    eventsTitle: '害怕在事件中得不到分数?',
    eventsSubtitle: '现在 Uncle ReVaN 教你怎么做',
    eventsDesc: '装备管理策略以保持精神力低',
    guardWeaponsStrategy: '护卫武器策略',
    guardWeaponsContent: '根据您的主要部队类型替换护卫武器:',
    equipStrategically: '骑兵: 用1-2-3或4级武器替换步兵和远程护卫武器',
    manageTroops: '远程: 用1-2-3或4级武器替换步兵和骑兵护卫武器',
    exceptionLeaders: '保持最优武器以保持精神力低',
    curiositiesManagement: '奇特物品管理',
    curiositiesContent: '根据您的主要部队类型替换奇特物品:',
    collectCombine: '骑兵: 用1-2-3或4级物品替换步兵和远程奇特物品',
    trackPowerChanges: '远程: 用1-2-3或4级物品替换步兵和骑兵奇特物品',
    planLoadouts: '保持最优奇特物品以保持精神力低',
     coaNew: '纹章 (新)',
     newestFeature: '根据您的主要部队类型用R17替换纹章:',
     applyCoa: '步兵和骑兵: 用R17纹章替换以降低精神力',
     calculateImpact: '远程: 用R17纹章替换',
     maximizePerformance: '例外: Rasse和Cristian被排除在此策略之外',
    copyright: 'Guns of Glory',
  },
  DE: {
    headerBranding: 'Gut Gemacht! Wir Sind Championregion!!',
    projectName: 'k698 - Wiedergeburtsprojekt',
    headerSubtitle: 'Jetzt versuchen wir, die Fehler zu beheben, bevor es zu spät ist',
    spiritualPowerTitle: 'Verwaltung der Spirituellen Kraft',
    spiritualPowerBanner: 'SPOILER ALERT: Dies ist kein Ratschlag und keine freundliche Bitte. Das ist eine Regel, die man befolgen muss.',
    spiritualPowerDesc: 'Lerne, wie du die spirituelle Kraft deines Königreichs während Events verwaltest',
    guardWeapons: 'Wachausrüstung',
    curiosities: 'Kuriositäten',
    coatsOfArms: 'Wappen',
    newBadge: 'Neu',
    eventsTitle: 'Angst, in Events keine Punkte zu machen?',
    eventsSubtitle: 'Jetzt erklärt dir Onkel ReVaN, wie man es macht',
    eventsDesc: 'Ausrüstungsverwaltungsstrategien um die spirituelle Kraft niedrig zu halten',
    guardWeaponsStrategy: 'Wachausrüstungsstrategie',
    guardWeaponsContent: 'Ersetzen Sie Wachausrüstung basierend auf Ihrem Haupttruppentyp:',
    equipStrategically: 'Kavallerie: Ersetzen Sie Infanterie- und Distanz-Wachausrüstung durch Waffen der Stufe 1-2-3 oder 4',
    manageTroops: 'Distanz: Ersetzen Sie Infanterie- und Kavallerie-Wachausrüstung durch Waffen der Stufe 1-2-3 oder 4',
    exceptionLeaders: 'Behalten Sie optimale Waffen, um die spirituelle Kraft niedrig zu halten',
    curiositiesManagement: 'Kuriositätenverwaltung',
    curiositiesContent: 'Ersetzen Sie Kuriositäten basierend auf Ihrem Haupttruppentyp:',
    collectCombine: 'Kavallerie: Ersetzen Sie Infanterie- und Distanz-Kuriositäten durch Gegenstände der Stufe 1-2-3 oder 4',
    trackPowerChanges: 'Distanz: Ersetzen Sie Infanterie- und Kavallerie-Kuriositäten durch Gegenstände der Stufe 1-2-3 oder 4',
    planLoadouts: 'Behalten Sie optimale Kuriositäten, um die spirituelle Kraft niedrig zu halten',
     coaNew: 'Wappen (Neu)',
     newestFeature: 'Ersetzen Sie Wappen basierend auf Ihrem Haupttruppentyp mit R17:',
     applyCoa: 'Infanterie und Kavallerie: Ersetzen Sie mit R17 Wappen für niedrigere spirituelle Kraft',
     calculateImpact: 'Distanz: Ersetzen Sie mit R17 Wappen',
     maximizePerformance: 'Ausnahme: Rasse und Cristian sind von dieser Strategie ausgeschlossen',
    copyright: 'Guns of Glory',
  },
  FR: {
    headerBranding: 'Bien Fait! Nous Sommes Région Championne!!',
    projectName: 'k698 - Projet Renaissance',
    headerSubtitle: 'Maintenant, essayons de corriger les erreurs commises avant qu\'il ne soit trop tard',
    spiritualPowerTitle: 'Gestion du Pouvoir Spirituel',
    spiritualPowerBanner: 'SPOILER ALERT: Ce n\'est pas un conseil, ni une demande amicale. C\'est une règle à suivre.',
    spiritualPowerDesc: 'Apprenez à gérer le pouvoir spirituel de votre royaume pendant les événements',
    guardWeapons: 'Armes de la Garde',
    curiosities: 'Curiosités',
    coatsOfArms: 'Blasons',
    newBadge: 'Nouveau',
    eventsTitle: 'Peur de ne pas scorer aux événements?',
    eventsSubtitle: 'Maintenant Oncle ReVaN t\'explique comment faire',
    eventsDesc: 'Stratégies de gestion des équipements pour maintenir le pouvoir spirituel bas',
    guardWeaponsStrategy: 'Stratégie des Armes de la Garde',
    guardWeaponsContent: 'Remplacez les Armes de la Garde selon votre type de troupes principales:',
    equipStrategically: 'Cavalerie: Remplacez les Armes de la Garde d\'Infanterie et Distanza par des armes de niveau 1-2-3 ou 4',
    manageTroops: 'Distanza: Remplacez les Armes de la Garde d\'Infanterie et Cavalerie par des armes de niveau 1-2-3 ou 4',
    exceptionLeaders: 'Conservez les armes optimales pour maintenir le pouvoir spirituel bas',
    curiositiesManagement: 'Gestion des Curiosités',
    curiositiesContent: 'Remplacez les Curiosités selon votre type de troupes principales:',
    collectCombine: 'Cavalerie: Remplacez les Curiosités d\'Infanterie et Distanza par des objets de niveau 1-2-3 ou 4',
    trackPowerChanges: 'Distanza: Remplacez les Curiosités d\'Infanterie et Cavalerie par des objets de niveau 1-2-3 ou 4',
    planLoadouts: 'Conservez les Curiosités optimales pour maintenir le pouvoir spirituel bas',
     coaNew: 'Blasons (Nouveau)',
     newestFeature: 'Remplacez les Blasons selon votre type de troupes principales avec R17:',
     applyCoa: 'Infanterie et Cavalerie: Remplacez avec des Blasons R17 pour un pouvoir spirituel inférieur',
     calculateImpact: 'Distanza: Remplacez avec des Blasons R17',
     maximizePerformance: 'Exception: Rasse et Cristian sont exclus de cette stratégie',
    copyright: 'Guns of Glory',
  },
  RU: {
    headerBranding: 'Отлично Сделано! Мы - Чемпионский Регион!!',
    projectName: 'k698 - Проект Возрождения',
    headerSubtitle: 'Теперь давайте попытаемся исправить ошибки, допущенные до того, как будет слишком поздно',
    spiritualPowerTitle: 'Управление Духовной Силой',
    spiritualPowerBanner: 'ВНИМАНИЕ СПОЙЛЕР: Это не совет и не дружеская просьба. Это правило, которое необходимо соблюдать.',
    spiritualPowerDesc: 'Узнайте, как управлять духовной силой вашего королевства во время событий',
    guardWeapons: 'Оружие Охраны',
    curiosities: 'Редкости',
    coatsOfArms: 'Гербы',
    newBadge: 'Новое',
    eventsTitle: 'Боишься не получить очки на событиях?',
    eventsSubtitle: 'Теперь Дядя ReVaN объясняет как это сделать',
    eventsDesc: 'Стратегии управления оружием для поддержания низкой духовной силы',
    guardWeaponsStrategy: 'Стратегия Оружия Охраны',
    guardWeaponsContent: 'Замените Оружие Охраны в зависимости от типа основных войск:',
    equipStrategically: 'Кавалерия: Замените Оружие Охраны Пехоты и Дальних на оружие уровня 1-2-3 или 4',
    manageTroops: 'Дальние: Замените Оружие Охраны Пехоты и Кавалерии на оружие уровня 1-2-3 или 4',
    exceptionLeaders: 'Сохраняйте оптимальное оружие, чтобы поддерживать низкую духовную силу',
    curiositiesManagement: 'Управление Редкостями',
    curiositiesContent: 'Замените Редкости в зависимости от типа основных войск:',
    collectCombine: 'Кавалерия: Замените Редкости Пехоты и Дальних на предметы уровня 1-2-3 или 4',
    trackPowerChanges: 'Дальние: Замените Редкости Пехоты и Кавалерии на предметы уровня 1-2-3 или 4',
    planLoadouts: 'Сохраняйте оптимальные Редкости, чтобы поддерживать низкую духовную силу',
     coaNew: 'Гербы (Новое)',
     newestFeature: 'Замените Гербы в зависимости от типа основных войск на R17:',
     applyCoa: 'Пехота и Кавалерия: Замените на Гербы R17 для более низкой духовной силы',
     calculateImpact: 'Дальние: Замените на Гербы R17',
     maximizePerformance: 'Исключение: Rasse и Cristian исключены из этой стратегии',
    copyright: 'Guns of Glory',
  },
  ES: {
    headerBranding: '¡Bien Hecho! ¡Somos la Región Campeona!!',
    projectName: 'k698 - Proyecto Renacimiento',
    headerSubtitle: 'Ahora intentemos recuperarnos de los errores cometidos antes de que sea demasiado tarde',
    spiritualPowerTitle: 'Gestión del Poder Espiritual',
    spiritualPowerBanner: 'ALERTA DE SPOILER: Esto no es un consejo, ni una solicitud amistosa. Es una regla que debe seguirse.',
    spiritualPowerDesc: 'Aprende cómo gestionar el poder espiritual de tu reino durante los eventos',
    guardWeapons: 'Armas de la Guardia',
    curiosities: 'Curiosidades',
    coatsOfArms: 'Escudos de Armas',
    newBadge: 'Nuevo',
    eventsTitle: '¿Miedo de no anotar puntos en los eventos?',
    eventsSubtitle: 'Ahora Tío ReVaN te explica cómo hacerlo',
    eventsDesc: 'Estrategias de gestión de equipos para mantener bajo el poder espiritual',
    guardWeaponsStrategy: 'Estrategia de Armas de la Guardia',
    guardWeaponsContent: 'Reemplaza las Armas de la Guardia según tu tipo de tropas principales:',
    equipStrategically: 'Caballería: Reemplaza las Armas de la Guardia de Infantería y Distancia con armas de nivel 1-2-3 o 4',
    manageTroops: 'Distancia: Reemplaza las Armas de la Guardia de Infantería y Caballería con armas de nivel 1-2-3 o 4',
    exceptionLeaders: 'Mantén las armas óptimas para mantener bajo el poder espiritual',
    curiositiesManagement: 'Gestión de Curiosidades',
    curiositiesContent: 'Reemplaza las Curiosidades según tu tipo de tropas principales:',
    collectCombine: 'Caballería: Reemplaza las Curiosidades de Infantería y Distancia con objetos de nivel 1-2-3 o 4',
    trackPowerChanges: 'Distancia: Reemplaza las Curiosidades de Infantería y Caballería con objetos de nivel 1-2-3 o 4',
    planLoadouts: 'Mantén las Curiosidades óptimas para mantener bajo el poder espiritual',
     coaNew: 'Escudos de Armas (Nuevo)',
     newestFeature: 'Reemplaza los Escudos de Armas según tu tipo de tropas principales con R17:',
     applyCoa: 'Infantería y Caballería: Reemplaza con Escudos de Armas R17 para menor poder espiritual',
     calculateImpact: 'Distancia: Reemplaza con Escudos de Armas R17',
     maximizePerformance: 'Excepción: Rasse y Cristian están excluidos de esta estrategia',
    copyright: 'Guns of Glory',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
